version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: libc
    versions:
    - 0.2.82
    - 0.2.84
    - 0.2.85
    - 0.2.86
    - 0.2.88
    - 0.2.90
    - 0.2.91
    - 0.2.92
  - dependency-name: domain
    versions:
    - 0.6.0
  - dependency-name: log
    versions:
    - 0.4.13
  - dependency-name: hyper
    versions:
    - 0.14.2
